---
name: Build and Push React App to Google Cloud Platform
on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: react-interpersonal-map
  REGION: northamerica-northeast1
  IMAGE_NAME: interpersonal-map-app

jobs:
  build-and-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate with Google Cloud
    - id: "auth"
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    # Setup gcloud CLI/SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Docker push
      run: gcloud auth configure-docker --quiet

    - name: Build Docker Image
      run: |-
        docker build -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v patch

    - name: Tag Docker image
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker image to Google Container Registry (GCR)
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Deploy
      run: |-
        gcloud run deploy $IMAGE_NAME --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest --region $REGION